version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: mindtrace-aj
    AWS_REGION: us-west-2

phases:
  pre_build:
    commands:
      - echo Getting AWS Account ID
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build completed successfully
