version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"
    ECR_REPO_NAME: "brain-tasks-repo"
    CLUSTER_NAME: "brain-cluster"

phases:

  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo Getting AWS Account ID...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - echo Updating Kubernetes deployment image...
      - kubectl set image deployment/brain-app brain-app=$REPOSITORY_URI:$IMAGE_TAG

      - echo Waiting for rollout to complete...
      - kubectl rollout status deployment/brain-app

artifacts:
  files:
    - '**/*'
