apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
        - name: brain-app
          image: 524781515606.dkr.ecr.us-west-2.amazonaws.com/brain-tasks-repo:v1
          ports:
            - containerPort: 80
